### ISSUE TITLE
WTF EVs and IVs?

### ISSUE THREAD

**Issue by aebooth** [aebooth/ZorCK2016#2]

**Comment by rallen198** [comment]
they are stupid and complex, that what they are. also a blatant ripoff of Pokemon.

**Comment by cuddleswithfish** [comment]
but if we wants to put in a specific, unique boss, the randoms will get it the ways of the balances.!

**Comment by m-99** [comment]
Please no. I don't want this to be Pokémon.
I don't even think we should have XP. Health is good enough.
The focus should be on the adventure, not the combat.

**Comment by InfiniteSchool** [comment]
map and movement first, combat stuff later

**Comment by sonicduck** [comment]
No, never. Do we really need to make this any more complicated than it already is? I mean, do we really need a complicated battle system like these values imply?

**Comment by marymattsen** [comment]
What if we have it like the first Zelda, where you don't have xp but you find better weapons as you explore

**Comment by BADayley** [comment]
i believe that they have nothing to do with this game so... we shouldn't include stuff we can't use! are we making pokemon? NO!!!

**Comment by ghost** [comment]
no. Zork is primarily a puzzle-adventure game with minimal combat. while there may be ways to make the implementation of EVs and IVs simple, the mechanic creates too much overhead.

**Comment by justmebhowd** [comment]
follow @nicolasstimac on soundcloud

**Comment by justmebhowd** [comment]
add me on craigslist
if you're buyin, i'm sellin ;)

**Comment by dwthomas16** [comment]
hey bhow ;) asl?

**Comment by dwthomas16** [comment]
18/m/wa

**Comment by justmebhowd** [comment]
14/f/wa

**Comment by dwthomas16** [comment]
jk im actually 15 bb

**Comment by sonicduck** [comment]
8/f/wa

**Comment by justmebhowd** [comment]
ayyyy lmao

**Comment by justmebhowd** [comment]
Who wants to go to Chungs

**Comment by hoyminoy** [comment]
97/m/wa hmu ;)

**Comment by sonicduck** [comment]
kik?

**Comment by justmebhowd** [comment]
Booth you comin?

**Comment by dwthomas16** [comment]
xXbigsexy69xX

**Comment by hoyminoy** [comment]
kik: MuscularMale6969

**Comment by hoyminoy** [comment]
for a good time call 1-800-EAT-THOSE

**Comment by sonicduck** [comment]
call me @ (696)-969-6969

**Comment by cuddleswithfish** [comment]
Ivs are great! For the morphine!

**Comment by sonicduck** [comment]
I prefer Ivy, like the league.

**Comment by aebooth** [comment]
All, for now I will switch this Pokemon style system to the "pokemon" branch which Aidan and others who are interested can maintain/develop.
