### ISSUE TITLE
Should we pursue making a project wiki?

### ISSUE THREAD

**Issue by m-99** [aebooth/ZorCK2016#3]
I'm worried that the people in charge of content might accidentally work on the same room, since it's so hard to communicate between two classes. 
Should we make a wiki for the purpose of keeping track who's working on what? 
Would this help us communicate between the class periods, or are Google Docs sufficient?
Do enough students even frequent GitHub enough to make this a worthwhile pursuit?

**Comment by AlexJ2** [comment]
I think a Google Doc could just cover this purpose, I'm not sure if a wiki is completely necessary, after all, we only have a few weeks of school left anyway.
